const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const ts = require('../node_modules/typescript');
const data = new Map();
const context = { exports: {}, Date, localStorage: { getItem: k => data.get(k), setItem: (k,v) => data.set(k,v) } };
vm.createContext(context);
vm.runInContext(ts.transpileModule(fs.readFileSync('src/music-lyrics.ts','utf8'), {compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText, context);
const {parseLrc, lyricIndex, musicTime, LyricStore} = context.exports;
const {lyricWords, wordProgress} = context.exports;
const enhanced = parseLrc('[offset:100]\n[00:01.00]<00:01.00>开<00:02.00>始<00:03.00>')[0];
const words = lyricWords(enhanced, 4);
assert.equal(enhanced.text, '开始'); assert.equal(words.length, 2);
assert.equal(words[0].at, .9); assert.equal(words[1].end, 2.9);
assert.ok(Math.abs(wordProgress(words[0], 1.4) - .5) < 1e-8);
assert.equal(wordProgress(words[0], 0), 0); assert.equal(wordProgress(words[0], 9), 1);
const estimated = lyricWords({at:3,text:'山海 Hello world'}, 9);
assert.equal(estimated.map(w=>w.text).join(''), '山海 Hello world');
assert.ok(Math.abs(estimated.at(-1).end - 9) < 1e-8);
assert.ok(lyricWords({at:3,text:'间奏之前'}, 100).at(-1).end <= 15.00001);
assert.equal(parseLrc('[00:01]<00:01>原文\n[00:01]译文')[0].words, undefined);
const lines = parseLrc('\uFEFF[ar:Artist]\r\n[offset:+100]\r\n[00:01.20][00:03.400]开学，适应ing......\r\n[00:03.400]无事发生......\n[00:04.00]\n[99:99]Invalid');
assert.equal(lines.length, 3);
assert.equal(lines[0].at, 1.0999999999999999);
assert.equal(lines[1].text, '开学，适应ing......\n无事发生......');
assert.equal(lyricIndex(lines, 0), -1); assert.equal(lyricIndex(lines, 3.4), 1);
assert.equal(lyricIndex([], 3), -1); assert.equal(musicTime(null), '—:—'); assert.equal(musicTime(177.8), '2:57');
const store = new LyricStore(); store.put('local', {syncedLyrics:'[00:01]Local'}, true);
store.put('local', {plainLyrics:'Online'}, false); assert.equal(store.get('local').local, true);
for(let i=0;i<90;i++) store.put(`online${i}`, {plainLyrics:String(i)}, false);
assert.equal(Object.keys(JSON.parse([...data.values()][0])).length,81);
store.remove('local'); assert.equal(store.get('local'),undefined);
console.log('PASS: timestamps, offsets, repeated tags, Chinese lines, timing lookup and bounded cache with protected local imports');
